language: objective-c

osx_image: xcode7.3

install:
  - npm install

script:
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi

env:
  matrix:
    - TEST_TYPE=e2e-objc
    - TEST_TYPE=objc
    - TEST_TYPE=js

branches:
  only:
    - master
